#!/bin/bash
# A combo of stuff from my prompt and some online Mac resources, e.g.:
# http://osxdaily.com/2013/02/05/improve-terminal-appearance-mac-os-x/
export PS1="\n\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h [\d]: \[\033[33;1m\]\w\[\033[m\]\n$ " 
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'
