#!/bin/bash
# Publish taurworks to PyPI via twine
# Requires:
# - python -m pip install twine
echo "Publishing taurworks to PyPI..."
set -x

if [ -d "dist" ]; then
    echo twine upload dist/*
    echo "Publishing not yet supported until taurworks is more heavily tested / fleshed out."
    EXIT_CODE=1

else
    echo "No dist directory found, please run build first."
    EXIT_CODE=1
fi

# Turn off logging and print a blank line
{ set +x; } 2>/dev/null
echo

# If the command failed, exit with the exit code
exit $EXIT_CODE
