#!/bin/bash
# Publish treemi to PyPI via twine
# Requires:
# - pip install twine
echo "Publishing treemi to pip..."
set -x

if [ -d "dist" ]; then
    echo twine upload dist/*
    echo "Publishing not yet supported until treemi is more heavily tested / fleshed out."
    exit 1 # replace with EXIT_CODE=$?

else
    echo "No dist directory found, please run build first."
    exit 1
fi

# Turn off logging and print a blank line
{ set +x; } 2>/dev/null
echo

# If the command failed, exit with the exit code
exit $EXIT_CODE
