#!/bin/bash
echo "Running unit/regression tests (excluding smoke tests)..."
set -x

if [ -d "tests" ]; then
    python -m unittest discover tests "*_test.py"
else
    python -m unittest discover . "*_test.py"
fi
EXIT_CODE=$?

{ set +x; } 2>/dev/null
echo

exit $EXIT_CODE
