#!/bin/bash
echo "Updating the Anaconda dependency listing..."
set -x

conda env export | egrep -v "^name:" | egrep -v "^prefix:" > environment.yml
EXIT_CODE=$?

# Turn off logging and print a blank line
{ set +x; } 2>/dev/null
echo

# If the command failed, exit with the exit code
exit $EXIT_CODE
